### ISSUE TITLE
google_distance >> lexical error: invalid char in json text

### ISSUE THREAD

**Issue by wsamuelw** [SymbolixAU/googleway#93] opened 2017-11-04 11:40 UTC
I have a data frame of 400+ locations stored in df SUBURB. I am trying to use the google_distance function to get the distance from A to B (many locations to one). It works fine when I am only doing [1:40]. 

Here are some sample values in the df.

`head(SUBURB$Full_Suburb)`
[1] "ALTONA NORTH, Victoria, Australia"  "BACCHUS MARSH, Victoria, Australia" "DIAMOND CREEK, Victoria, Australia"
[4] "ELWOOD, Victoria, Australia"        "KEILOR EAST, Victoria, Australia"   "MORDIALLOC, Victoria, Australia"  

With the following code, I am doing [1:41]. I get this error below.

Error: lexical error: invalid char in json text.
                                       https://maps.googleapis.com/map
                     (right here) ------^

```
dist <- google_distance(origins = SUBURB$Full_Suburb[1:41],
                              destinations = SUBURB$Destination[1],
                              mode = "driving",
                              arrival_time = local,
                              key = key,
                              simplify = T)
```

I have also tried turning this df into a list to see if it works. I got the same error.

```
dist <- google_distance(origins = sub[1:45],
                               destinations = des[1],
                               mode = "driving",
                               arrival_time = local,
                               key = key,
                               simplify = T)

```

**Comment by SymbolixAU** [comment] 2017-11-08 04:54
does it work for `[10:51]` ?

You might be hitting the [limits](https://developers.google.com/maps/documentation/distance-matrix/usage-limits) allowed by the API, or the potential the [maximum length](https://stackoverflow.com/a/417184/5977215) of a valid URL?

**Comment by SymbolixAU** [comment] 2017-12-08 21:11
If there's no follow-up to this I'll close it

**Comment by qilingit** [comment] 2018-04-30 15:14
Same problem for `google_place`, problem solved with encoding url to UTF-8, modify code of function `google_places.R` below: 
`map_url <- content(GET(map_url), as = "text", encoding = "UTF-8")`
I wish this can be help

**Comment by SymbolixAU** [comment] 2018-04-30 21:46
@qilingit do you have example data I can use to reproduce this error?

**Comment by SymbolixAU** [comment] 2018-04-30 23:26
@qilingit Can you give a single row of `geoCodingInfo` which causes the error?

**Comment by qilingit** [comment] 2018-04-30 23:38
@SymbolixAU Sorry for my level of R, I've checkout that the type of geoCodingInfo is a list, the type of element is double, so you can define geoCodingInfo like this : list(48.849276, 2.331166).

Error is below:
`Error: lexical error: invalid char in json text.
                                       https://maps.googleapis.com/map
                     (right here) ------^ `

**Comment by SymbolixAU** [comment] 2018-04-30 23:42
@qilingit is your issue specifically with this line of code:

```
geoCodingInfo <- list(48.849276, 2.331166)

library(googleway)
set_key("GOOGLE_API_KEY")

resultRestau <- google_places(
	location = c(geoCodingInfo[[1]], geoCodingInfo[[2]]), 
	radius = 300, 
	rankby = "prominence", 
	language = "fr", 
	place_type = "restaurant", 
	simplify = TRUE
	)
```

Because this does not error for me?

**Comment by qilingit** [comment] 2018-04-30 23:48
@SymbolixAU 
I don't understand clearly, because when I tryed with a line, it's true. But when we search with a place that contains many restaurants, for exemple more than 60 with a radius of 300 meters. 

When we try with **geoCondingInfo <- c(48.8745651, 2.3047421),** it will be have an error when it takes to the third loop: 
`resultRestau_next2 <- google_places(location = c(geoCodingInfo[1,1], geoCodingInfo[1, 2]), radar = FALSE, radius = 300, rankby = "prominence", 
                                              language = "fr", place_type = "restaurant", page_token = resultRestau_next1$next_page_token, simplify = TRUE, key = placesKey)`

**Comment by SymbolixAU** [comment] 2018-04-30 23:52
@qilingit - OK, I can now reproduced the error with

```
geoCodingInfo <- list(48.849276, 2.331166)

library(googleway)
set_key(read.dcf("~/Documents/.googleAPI", fields = "GOOGLE_API_KEY"))

resultRestau <- google_places(
	location = c(geoCodingInfo[[1]], geoCodingInfo[[2]]), 
	radius = 300, 
	rankby = "prominence", 
	language = "fr", 
	place_type = "restaurant", 
	simplify = TRUE
	)

resultRestau_next2 <- google_places(
	location = c(geoCodingInfo[[1]], geoCodingInfo[[2]]), 
	radar = FALSE, 
	radius = 300, 
	rankby = "prominence", 
	language = "fr", 
	place_type = "restaurant", 
	page_token = place_next_page(resultRestau), 
	simplify = TRUE
	)

resultRestau_next3 <- google_places(
	location = c(geoCodingInfo[[1]], geoCodingInfo[[2]]), 
	radar = FALSE, 
	radius = 300, 
	rankby = "prominence", 
	language = "fr", 
	place_type = "restaurant", 
	page_token = place_next_page(resultRestau_next2), 
	simplify = TRUE
)
```

I'll have a look and get back to you.

**Comment by qilingit** [comment] 2018-04-30 23:56
@SymbolixAU 
Thanks, I've solved with adding a line in function google_places.R to encoding url to UTF-8 like below:
`  map_url <- constructURL(map_url, c(location = location, 
    radius = radius, rankby = rankby, keyword = keyword, 
    language = language, name = name, type = place_type, 
    minprice = price_range[1], maxprice = price_range[2], 
    opennow = open_now, pagetoken = page_token, key = key))
  map_url <- content(GET(map_url), as = "text", encoding = "UTF-8")
  return(downloadData(map_url, simplify, curl_proxy))`

I wish this can help and can you come back to me when you find out the reason please?

**Comment by SymbolixAU** [comment] 2018-05-01 01:11
@qilingit - I've created a branch and made a change to the `downloadData` function 
https://github.com/SymbolixAU/googleway/commit/20d5f86fe188b14f334a0cdc558873b3e4eb47f0

Could you download this latest version and see if it works for you? 

Install it with

```
devtools::install_github("SymbolixAU/googlweay", ref = "curl")
```

merci

**Comment by qilingit** [comment] 2018-05-01 01:24
@SymbolixAU 
It works, there isn't this type of error anymore, you can commit it to the master branch. 
Thanks very much, merci beaucoup!

**Comment by SymbolixAU** [comment] 2018-05-01 01:26
@qilingit  I'll need to keep testing it for a while to make sure the other functions still work as expected, but I should merge it in the next few days. 

Thanks for finding & reporting the issue.

**Comment by qilingit** [comment] 2018-05-01 01:28
@SymbolixAU 
No problem with that, it's a pleasure to solve un problem, looking forward to yours work.

**Comment by SymbolixAU** [comment] 2018-05-02 21:52
Let's call that a fix then. Thanks @AmeliaMN

**Closed** 2018-05-02 21:51 UTC
