### ISSUE TITLE
Vignette add_polygons() example returning error 

### ISSUE THREAD

**Issue by smach** [SymbolixAU/googleway#114] opened 2018-01-20 16:48 UTC
I am trying to run the vignette example

    nc <- sf::st_read(system.file("shape/nc.shp", package="sf"))
    google_map(data = nc, key = key) %>%
      add_polygons()

but receive the following error: 

    Error in latLonPolyCheck(lat, lon, polyline) : 
      please supply the either the column containing the polylines, or the lat/lon coordinate columns

I am using the GitHub version of googleway and latest CRAN version of sf running on Windows 10 with R 3.4.1. My API key does work if I create the map without the polygons (I get the expected map centered in Melbourne). Thanks.

**Comment by SymbolixAU** [comment] 2018-01-21 07:50
@smach  The Vignette is a little ahead of the master branch at the moment, as I'm waiting for another package to be updated on CRAN before I completely get the `sf` objects working. You just happen to have read the updated vignette in this 'in-between' stage of getting everything updated at the same time.

However, if you install the `sf` branch, you should see it working

```
devtools::install_github("SymbolixAU/googleway", ref = "sf")
```

**Comment by smach** [comment] 2018-01-21 17:45
Cool, thanks.  I tried installing the sf branch and it still didn't seem to work, but I'll just wait for the CRAN version and try again. Thanks for the package!

**Comment by SymbolixAU** [comment] 2018-01-21 21:31
@smach I'm re-opening this because you couldn't get the branch to work - so there's something I need to fix.

**Comment by SymbolixAU** [comment] 2018-01-22 10:51
@smach I think you can get the `sf` branch working if you install the dev branch of `googlePolylines`

```
devtools::install_github("SymbolixAU/googlePolylines")
```

(this is the package I'm also updating on which `googleway` will depend for `sf` objects)

**Comment by SymbolixAU** [comment] 2018-01-26 11:42
@smach - my other package `googlePolylines` has been updated on CRAN, so I've merged the `sf` branch of `googleway` into the master branch, so you should be able to install it as per usual

```
devtools::install_github("SymbolixAU/googleway")
```

and you should be able to plot the `sf` object.

Could you try this again and see if it works for you?

**Comment by SymbolixAU** [comment] 2018-02-02 00:22
I'm closing this issue because I can't reproduce the error, and version 2.4 is now on CRAN.

**Closed by SymbolixAU** 2018-02-02 00:22 UTC
